package Start;


import Users.userDashboard;
import admin.admin_dashboard;
import config.Session;
import config.dbConnector;
import config.passHash;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SCC-COLLEGE
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    public loginform() {
        initComponents();
    }
   
    static String status;
    static String type;
    
    public static boolean loginAcc(String username, String password){
        dbConnector connector = new dbConnector();
        try{
            String query = "SELECT * FROM tbl_user WHERE u_username = '" + username + "'";
            ResultSet resultSet = connector.getData(query);
            if(resultSet.next()){
                String hashedPass = resultSet.getString("u_pass");
                String rehashedPass = passHash.hashPassword(password);
                if(hashedPass.equals(rehashedPass)){
                    status = resultSet.getString("u_status");
                    type = resultSet.getString("u_type");
                        Session sess = Session.getInstance();
                        sess.setUid(resultSet.getInt("u_id"));
                        sess.setFname(resultSet.getString("u_fname"));
                        sess.setLname(resultSet.getString("u_lname"));
                        sess.setEmail(resultSet.getString("u_email"));
                        sess.setUsername(resultSet.getString("u_username"));
                        sess.setType(resultSet.getString("u_type"));
                        sess.setStatus(resultSet.getString("u_status"));
                        return true;
                }else{
                    return false;
                }  
            }else{
                return false;
            }
            }catch (SQLException | NoSuchAlgorithmException ex){
                return false;
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txf = new javax.swing.JLabel();
        grant = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        sca = new javax.swing.JLabel();
        creat = new javax.swing.JButton();
        log = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        uname1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cash app icon.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 660, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 590));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txf.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        txf.setForeground(new java.awt.Color(255, 255, 255));
        txf.setText("PASSWORD");
        jPanel2.add(txf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, 30));

        grant.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        grant.setForeground(new java.awt.Color(255, 255, 255));
        grant.setText("GRANT!");
        jPanel2.add(grant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 60));

        uname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uname.setText("Forgot Password? Click here");
        uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unameMouseClicked(evt);
            }
        });
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 230, 30));

        sca.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        sca.setForeground(new java.awt.Color(255, 255, 255));
        sca.setText("STUDENT CASH ASSISTANCE");
        jPanel2.add(sca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 370, 60));

        creat.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        creat.setText("CREAT ACCOUNT");
        creat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatMouseClicked(evt);
            }
        });
        creat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatActionPerformed(evt);
            }
        });
        jPanel2.add(creat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 160, 30));

        log.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        log.setText("LOGIN");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel2.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, 30));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 230, 30));

        uname1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        uname1.setForeground(new java.awt.Color(255, 255, 255));
        uname1.setText("USERNAME");
        jPanel2.add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 500, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatActionPerformed
        regisform rf = new regisform();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creatActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
    if(loginAcc(username.getText(), pass.getText())){
        if(!status.equals("Active")){
            JOptionPane.showMessageDialog(this, "In-Active Account contact Admin", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(type.equals("Admin")){
                JOptionPane.showMessageDialog(null, "Login Successfully!");
                admin_dashboard ad = new admin_dashboard();
                dbConnector dbc = new dbConnector();
                Session sess = Session.getInstance();
                dbc.logActivity(sess.getUid(), "User Login:" +sess.getLname());
                ad.setVisible(true);
                this.dispose();
            }else if(type.equals("Applicant")){
                JOptionPane.showMessageDialog(null, "Login Successfully!");
                userDashboard ud = new userDashboard();
                dbConnector dbc = new dbConnector();
                Session sess = Session.getInstance();
                dbc.logActivity2(sess.getUid(), "User Login:" +sess.getLname());
                ud.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "No Account type found contact the Admin", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }else{
        JOptionPane.showMessageDialog(this, "Invalid Account", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logActionPerformed

    private void creatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatMouseClicked
        regisform rf = new regisform();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creatMouseClicked

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked

    }//GEN-LAST:event_logMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void unameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMouseClicked
    emailSearch es = new emailSearch();
    es.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_unameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creat;
    private javax.swing.JLabel grant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton log;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel sca;
    private javax.swing.JLabel txf;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel uname1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
