/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Start.loginform;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class assistanceProgram extends javax.swing.JFrame {

    /**
     * Creates new form user_dashboard
     */
    public assistanceProgram() {
        initComponents();
        displayprograms();
    }
    
    public void displayprograms() {
        try {
            dbConnector db = new dbConnector();
            ResultSet rs = db.getData(
                "SELECT * FROM tbl_program");
            progtbl.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
        Color navcolor = new Color(255,255,255);  
        Color hovercolor = new Color (0, 255, 255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        progtbl = new javax.swing.JTable();
        dash3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        dash4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        dash5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        dash6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        wc = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dash1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        dash2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        dash7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cash Assistance Programs");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 45));

        progtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(progtbl);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 570, 340));

        dash3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash3MouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Delete Program");

        javax.swing.GroupLayout dash3Layout = new javax.swing.GroupLayout(dash3);
        dash3.setLayout(dash3Layout);
        dash3Layout.setHorizontalGroup(
            dash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dash3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        dash3Layout.setVerticalGroup(
            dash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(dash3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 140, 40));

        dash4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash4MouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("View Program");

        javax.swing.GroupLayout dash4Layout = new javax.swing.GroupLayout(dash4);
        dash4.setLayout(dash4Layout);
        dash4Layout.setHorizontalGroup(
            dash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dash4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );
        dash4Layout.setVerticalGroup(
            dash4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(dash4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 130, 40));

        dash5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash5MouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Add Program");

        javax.swing.GroupLayout dash5Layout = new javax.swing.GroupLayout(dash5);
        dash5.setLayout(dash5Layout);
        dash5Layout.setHorizontalGroup(
            dash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dash5Layout.setVerticalGroup(
            dash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(dash5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 40));

        dash6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash6MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Edit Program");

        javax.swing.GroupLayout dash6Layout = new javax.swing.GroupLayout(dash6);
        dash6.setLayout(dash6Layout);
        dash6Layout.setHorizontalGroup(
            dash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        dash6Layout.setVerticalGroup(
            dash6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(dash6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 600, 550));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 36, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setText("Log Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 70, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setText("SCA");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 42, -1));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 485, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setText("ADMIN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 495, -1, 40));

        wc.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        wc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(wc, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 147, 157, 43));

        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("User");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Assistance Program");

        javax.swing.GroupLayout dashLayout = new javax.swing.GroupLayout(dash);
        dash.setLayout(dashLayout);
        dashLayout.setHorizontalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashLayout.setVerticalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 40));

        dash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash1MouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dashboard");

        javax.swing.GroupLayout dash1Layout = new javax.swing.GroupLayout(dash1);
        dash1.setLayout(dash1Layout);
        dash1Layout.setHorizontalGroup(
            dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dash1Layout.setVerticalGroup(
            dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 40));

        dash2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash2MouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Approve Students");

        javax.swing.GroupLayout dash2Layout = new javax.swing.GroupLayout(dash2);
        dash2.setLayout(dash2Layout);
        dash2Layout.setHorizontalGroup(
            dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dash2Layout.setVerticalGroup(
            dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 40));

        dash7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash7MouseExited(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Release Cash");

        javax.swing.GroupLayout dash7Layout = new javax.swing.GroupLayout(dash7);
        dash7.setLayout(dash7Layout);
        dash7Layout.setHorizontalGroup(
            dash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dash7Layout.setVerticalGroup(
            dash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid() == 0){
            System.out.println("");
       }else{
            wc.setText(""+sess.getLname());
       } 
    }//GEN-LAST:event_formWindowActivated

    private void dash3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseClicked
    int rowindex = progtbl.getSelectedRow();
        if(rowindex < 0){
            JOptionPane.showMessageDialog(null, "Please Select an item!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this program?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                dbConnector dbc = new dbConnector();
                TableModel model = progtbl.getModel();
                String id = model.getValueAt(rowindex, 0).toString();
                dbc.updateData("DELETE FROM tbl_progran WHERE prog_id = '" + id + "'");
                Session sess = Session.getInstance();
                dbc.logActivity(sess.getUid(), "Deleted program ID: " + id);
                displayprograms();
                JOptionPane.showMessageDialog(null, "Program deleted successfully!");
            }
        }
    }//GEN-LAST:event_dash3MouseClicked

    private void dash3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash3MouseEntered

    private void dash3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash3MouseExited

    private void dash4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash4MouseClicked
    int rowIndex = progtbl.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null,"Please Select an Item!");
        }else{
            try{

                dbConnector dbc = new dbConnector();
                TableModel tbl = progtbl.getModel();
                ResultSet rst = dbc.getData("SELECT * FROM tbl_program WHERE prog_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
                if(rst.next()){
                    viewAssistanceProgram vap = new viewAssistanceProgram();
                    vap.progid.setText(""+rst.getInt("prog_id"));
                    vap.progname.setText(""+rst.getString("prog_name"));
                    vap.progdes.setText(""+rst.getString("prog_description"));
                    vap.applimit.setText(""+rst.getString("prog_applicantLimit"));
                    vap.totalfunds.setText(""+rst.getString("prog_allocatedFund"));
                    vap.setVisible(true);
                    this.dispose();
                }
            }catch(SQLException ex){
                System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_dash4MouseClicked

    private void dash4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash4MouseEntered

    private void dash4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash4MouseExited

    private void dash5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseClicked
    assistanceProgram1 ap1 = new assistanceProgram1();
    ap1.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_dash5MouseClicked

    private void dash5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash5MouseEntered

    private void dash5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash5MouseExited

    private void dash6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash6MouseClicked
    int rowIndex = progtbl.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null,"Please Select an Item!");
        }else{
            try{

                dbConnector dbc = new dbConnector();
                TableModel tbl = progtbl.getModel();
                ResultSet rst = dbc.getData("SELECT * FROM tbl_program WHERE prog_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
                if(rst.next()){
                    editAssistanceProgram eap = new editAssistanceProgram();
                    eap.progid.setText(""+rst.getInt("prog_id"));
                    eap.progname.setText(""+rst.getString("prog_name"));
                    eap.progdes.setText(""+rst.getString("prog_description"));
                    eap.setVisible(true);
                    this.dispose();
                }
            }catch(SQLException ex){
                System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_dash6MouseClicked

    private void dash6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash6MouseEntered

    private void dash6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash6MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        loginform lf = new loginform();
        JOptionPane.showMessageDialog(null,"User Logout Successfully!");
        dbConnector dbc = new dbConnector();
        Session sess = Session.getInstance();
        dbc.logActivity(sess.getUid(), "User Logout:" +sess.getLname());
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user_dashboard ud = new user_dashboard();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        user.setBackground(hovercolor);
    }//GEN-LAST:event_userMouseEntered

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        user.setBackground(navcolor);
    }//GEN-LAST:event_userMouseExited

    private void dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseClicked
        assistanceProgram ap = new assistanceProgram();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashMouseClicked

    private void dashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseEntered
        dash.setBackground(hovercolor);
    }//GEN-LAST:event_dashMouseEntered

    private void dashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseExited
        dash.setBackground(navcolor);
    }//GEN-LAST:event_dashMouseExited

    private void dash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseClicked
        admin_dashboard ad = new admin_dashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash1MouseClicked

    private void dash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseEntered

    private void dash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseExited

    private void dash2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseClicked
        ApprovedStudents as = new ApprovedStudents();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash2MouseClicked

    private void dash2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash2MouseEntered

    private void dash2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash2MouseExited

    private void dash7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseClicked
        cashReleasing cr = new cashReleasing();
        cr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash7MouseClicked

    private void dash7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash7MouseEntered

    private void dash7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assistanceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assistanceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assistanceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assistanceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assistanceProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dash;
    private javax.swing.JPanel dash1;
    private javax.swing.JPanel dash2;
    private javax.swing.JPanel dash3;
    private javax.swing.JPanel dash4;
    private javax.swing.JPanel dash5;
    private javax.swing.JPanel dash6;
    private javax.swing.JPanel dash7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTable progtbl;
    private javax.swing.JPanel user;
    private javax.swing.JLabel wc;
    // End of variables declaration//GEN-END:variables
}
