/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author SCC-COLLEGE
 */
public class cashReleasing2 extends javax.swing.JFrame {

    /**
     * Creates new form user_dashboard
     */
    public cashReleasing2() {
        initComponents();
        loadApplicant();
        loadProgram();
        
    }
    
    
    private HashMap<String, Integer> applicantMap = new HashMap<>();
    private HashMap<String, Integer> programtMap = new HashMap<>();  
    
    public void loadProgram(){
        dbConnector db = new dbConnector();
        try {
            String query = "SELECT prog_id, prog_name FROM tbl_program ORDER BY prog_name";
            ResultSet rs = db.getData(query);

            progname.removeAllItems();
            programtMap.clear(); 
            boolean hasProgram = false;

            while (rs.next()) {
                    hasProgram = true;
                    int progId = rs.getInt("prog_id");
                    String progName = rs.getString("prog_name");
                    progname.addItem(progName);
                    programtMap.put(progName, progId);
            }

            progname.revalidate();
            progname.repaint();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading program: " + e.getMessage());
        }
    }
    
    private void loadApplicant() {
    try {
        dbConnector db = new dbConnector();

        String query = "SELECT a.app_id, u.u_fname, u.u_lname " +  
               "FROM tbl_user u " +
               "INNER JOIN tbl_applicant a ON u.u_id = a.app_uid " +  
               "WHERE u.u_type = 'Applicant' " +
               "AND a.app_status = 'Accepted' " +
               "AND a.app_id NOT IN (SELECT cash_appid FROM tbl_cashreleasing) " +  
               "ORDER BY u.u_fname";
        
        ResultSet rs = db.getData(query);

        appname.removeAllItems();
        applicantMap.clear();

        boolean hasApplicants = false;
        while (rs.next()) {
            hasApplicants = true;
            int applicantId = rs.getInt("app_id");
            String fullName = rs.getString("u_fname") + " " + rs.getString("u_lname");
            appname.addItem(fullName);
            applicantMap.put(fullName, applicantId);
        }

        rs.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error loading applicants: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
    }
}
    
        Color navcolor = new Color(255,255,255);  
        Color hovercolor = new Color (0, 255, 255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        cnl = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cnl1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        appname = new javax.swing.JComboBox<>();
        progname = new javax.swing.JComboBox<>();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnlMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Release");

        javax.swing.GroupLayout cnlLayout = new javax.swing.GroupLayout(cnl);
        cnl.setLayout(cnlLayout);
        cnlLayout.setHorizontalGroup(
            cnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        cnlLayout.setVerticalGroup(
            cnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(cnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Applicant Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Release Cash");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Program Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));

        cnl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnl1MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Back");

        javax.swing.GroupLayout cnl1Layout = new javax.swing.GroupLayout(cnl1);
        cnl1.setLayout(cnl1Layout);
        cnl1Layout.setHorizontalGroup(
            cnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        cnl1Layout.setVerticalGroup(
            cnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(cnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, 40));
        jPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, 30));

        appname.setEnabled(false);
        jPanel1.add(appname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        progname.setEnabled(false);
        jPanel1.add(progname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid() == 0){
            JOptionPane.showMessageDialog(this, "Failed to open page. Please Login First.", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_formWindowActivated

    private void cnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseClicked
    String releaseCash = cash.getText().trim();
    String selectedApplicant = appname.getSelectedItem().toString();
    String selectedProgram = progname.getSelectedItem().toString();

    if (releaseCash.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Release Cash field is required!", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!releaseCash.matches("^\\d+(\\.\\d{1,2})?$")) { 
        JOptionPane.showMessageDialog(this, "Release cash should be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
        cash.setText("");
    } else if ("Please Select Applicant".equals(selectedApplicant) || "N/A".equals(selectedApplicant)) {
        JOptionPane.showMessageDialog(this, "Please select a valid applicant", "Error", JOptionPane.ERROR_MESSAGE);
    } else if ("Please Select Program".equals(selectedProgram) || "N/A".equals(selectedProgram)) { 
        JOptionPane.showMessageDialog(this, "Please select a valid program", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        dbConnector db = new dbConnector();
        Integer userId = applicantMap.get(selectedApplicant);
        Integer progId = programtMap.get(selectedProgram);

        String insertQuery = "INSERT INTO tbl_cashreleasing (cash_appid, cash_release, cash_progid) VALUES (?, ?, ?)";
        try (PreparedStatement pstmt = db.connect.prepareStatement(insertQuery)) {
            pstmt.setInt(1, userId);
            pstmt.setString(2, releaseCash);
            pstmt.setInt(3, progId);

            if (pstmt.executeUpdate() == 1) {
                Session sess = Session.getInstance();
                db.logActivity(sess.getUid(), "Released Cash Assistance to: " + userId);
                JOptionPane.showMessageDialog(this, "Release Cash Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                cashReleasing ef = new cashReleasing();
                ef.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to release cash");
            }
        } catch (SQLException ex) {
            System.out.println(""+ex);
            JOptionPane.showMessageDialog(null, "Database error occurred");
        }
    }
    }//GEN-LAST:event_cnlMouseClicked

    private void cnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cnlMouseEntered

    private void cnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cnlMouseExited

    private void cnl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnl1MouseClicked
    cashReleasing cr = new cashReleasing();
    cr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_cnl1MouseClicked

    private void cnl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cnl1MouseEntered

    private void cnl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnl1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cnl1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashReleasing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashReleasing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashReleasing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashReleasing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashReleasing2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> appname;
    public javax.swing.JTextField cash;
    private javax.swing.JPanel cnl;
    private javax.swing.JPanel cnl1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    public javax.swing.JComboBox<String> progname;
    // End of variables declaration//GEN-END:variables
}
