/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Start.loginform;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COLLEGE
 */
public class cashReleasing extends javax.swing.JFrame {

    /**
     * Creates new form user_dashboard
     */
    public cashReleasing() {
        initComponents();
        displayApplication();
    }
    
    public void displayApplication() {
    dbConnector db = null;
    ResultSet rs = null;
    
    try {
        db = new dbConnector();
        String query = 
            "SELECT app_id AS 'Application ID', " +
            "       CONCAT(u_fname, ' ', u_lname) AS 'Full Name', " +
            "       app_progname AS 'Program Name', " +
            "       cash_release AS 'Cash Release', " +
            "       app_status AS 'Status' " +
            "FROM tbl_user " +
            "INNER JOIN tbl_applicant ON u_id = app_uid " + 
            "INNER JOIN tbl_cashreleasing ON cash_appid = app_id " +
            "WHERE app_status = 'Accepted'";
        rs = db.getData(query);

        tblapplication.setModel(DbUtils.resultSetToTableModel(rs));
        
    } catch (SQLException e) {

    }
}
    
        Color navcolor = new Color(255,255,255);  
        Color hovercolor = new Color (0, 255, 255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblapplication = new javax.swing.JTable();
        dash3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        dash5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        wc = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dash = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dash1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        dash2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        dash7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Release Cash Assitance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 224, 45));

        tblapplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblapplication);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 570, 340));

        dash3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash3MouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Print Cash Release");

        javax.swing.GroupLayout dash3Layout = new javax.swing.GroupLayout(dash3);
        dash3.setLayout(dash3Layout);
        dash3Layout.setHorizontalGroup(
            dash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dash3Layout.setVerticalGroup(
            dash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(dash3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, 40));

        dash5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash5MouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Cash Release");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dash5Layout = new javax.swing.GroupLayout(dash5);
        dash5.setLayout(dash5Layout);
        dash5Layout.setHorizontalGroup(
            dash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        dash5Layout.setVerticalGroup(
            dash5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(dash5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 600, 550));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 36, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel5.setText("Log Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 70, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel7.setText("SCA");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, 42, -1));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 485, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setText("ADMIN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 495, -1, 40));

        wc.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        wc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(wc, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 147, 157, 43));

        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("User");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Assistance Program");

        javax.swing.GroupLayout dashLayout = new javax.swing.GroupLayout(dash);
        dash.setLayout(dashLayout);
        dashLayout.setHorizontalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashLayout.setVerticalGroup(
            dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 40));

        dash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash1MouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dashboard");

        javax.swing.GroupLayout dash1Layout = new javax.swing.GroupLayout(dash1);
        dash1.setLayout(dash1Layout);
        dash1Layout.setHorizontalGroup(
            dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dash1Layout.setVerticalGroup(
            dash1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 40));

        dash2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash2MouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Approve Students");

        javax.swing.GroupLayout dash2Layout = new javax.swing.GroupLayout(dash2);
        dash2.setLayout(dash2Layout);
        dash2Layout.setHorizontalGroup(
            dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dash2Layout.setVerticalGroup(
            dash2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 40));

        dash7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash7MouseExited(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Release Cash");

        javax.swing.GroupLayout dash7Layout = new javax.swing.GroupLayout(dash7);
        dash7.setLayout(dash7Layout);
        dash7Layout.setHorizontalGroup(
            dash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        dash7Layout.setVerticalGroup(
            dash7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dash7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(dash7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid() == 0){
            System.out.println("");
       }else{
            wc.setText(""+sess.getLname());
       } 
    }//GEN-LAST:event_formWindowActivated

    private void dash3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseClicked
    int rowIndex = tblapplication.getSelectedRow();

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please Select an Item!");
    } else {
        try {
            dbConnector dbc = new dbConnector();
            TableModel tbl = tblapplication.getModel();
            String appId = tbl.getValueAt(rowIndex, 0).toString();

            String query = "SELECT " +
                                "app_id AS 'Application ID', " +
                                "CONCAT(u_fname, ' ', u_lname) AS full_name, " +
                                "app_progname AS program_name, " +
                                "cash_release, " +
                                "app_status " +
                                "FROM tbl_user " +
                                "INNER JOIN tbl_applicant ON u_id = app_uid " + 
                                "INNER JOIN tbl_cashreleasing ON cash_appid = app_id " +
                                "WHERE app_id = '"+appId+"'";

            ResultSet rst = dbc.getData(query);

            if (rst.next()) {
                printAssistanceResults cr2 = new printAssistanceResults();

                cr2.appname.setText(rst.getString("full_name"));
                cr2.progname.setText(rst.getString("program_name"));
                cr2.cash.setText(rst.getString("cash_release"));

                cr2.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No application data found");
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex);
            JOptionPane.showMessageDialog(null, 
                "Database error: " + ex.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
}
    }//GEN-LAST:event_dash3MouseClicked

    private void dash3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash3MouseEntered

    private void dash3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash3MouseExited

    private void dash5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseClicked
    int rowIndex = tblapplication.getSelectedRow();
    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select an item first!", "Selection Required", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            dbConnector dbc = new dbConnector();
            TableModel tbl = tblapplication.getModel();
            String appId = tbl.getValueAt(rowIndex, 0).toString();

            ResultSet rst = dbc.getData(
                "SELECT u_fname, u_lname, app_progname FROM tbl_applicant INNER JOIN tbl_user ON app_uid = u_id WHERE app_id = '" + appId + "'");

            if (rst.next()) {
                cashReleasing2 cr2 = new cashReleasing2();

                String fullName = rst.getString("u_fname") + " " + rst.getString("u_lname");
                cr2.appname.setSelectedItem(fullName);
                cr2.progname.setSelectedItem("app_progname");

                cr2.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No application data found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                "Error loading applicant data: " + ex.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_dash5MouseClicked

    private void dash5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash5MouseEntered

    private void dash5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        loginform lf = new loginform();
        JOptionPane.showMessageDialog(null,"User Logout Successfully!");
        dbConnector dbc = new dbConnector();
        Session sess = Session.getInstance();
        dbc.logActivity(sess.getUid(), "User Logout:" +sess.getLname());
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        user_dashboard ud = new user_dashboard();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        user.setBackground(hovercolor);
    }//GEN-LAST:event_userMouseEntered

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        user.setBackground(navcolor);
    }//GEN-LAST:event_userMouseExited

    private void dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseClicked
        assistanceProgram ap = new assistanceProgram();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashMouseClicked

    private void dashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseEntered
        dash.setBackground(hovercolor);
    }//GEN-LAST:event_dashMouseEntered

    private void dashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseExited
        dash.setBackground(navcolor);
    }//GEN-LAST:event_dashMouseExited

    private void dash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseClicked
        admin_dashboard ad = new admin_dashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash1MouseClicked

    private void dash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseEntered

    private void dash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseExited

    private void dash2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseClicked
        ApprovedStudents as = new ApprovedStudents();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash2MouseClicked

    private void dash2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash2MouseEntered

    private void dash2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash2MouseExited

    private void dash7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseClicked
        cashReleasing cr = new cashReleasing();
        cr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dash7MouseClicked

    private void dash7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash7MouseEntered

    private void dash7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash7MouseExited

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashReleasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashReleasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashReleasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashReleasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashReleasing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dash;
    private javax.swing.JPanel dash1;
    private javax.swing.JPanel dash2;
    private javax.swing.JPanel dash3;
    private javax.swing.JPanel dash5;
    private javax.swing.JPanel dash7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JTable tblapplication;
    private javax.swing.JPanel user;
    private javax.swing.JLabel wc;
    // End of variables declaration//GEN-END:variables
}
