/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.PanelPrinter;
import config.Session;
import config.dbConnector;
import javax.swing.JPanel;

/**
 *
 * @author Chris
 */
public class printAssistanceResults extends javax.swing.JFrame {

    /**
     * Creates new form printResult
     */
    public printAssistanceResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        page = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        progname = new javax.swing.JLabel();
        appname = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 242, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("St. Cecilia's College - Cebu, Inc.");
        page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LASSO Supervised School");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Poblacion Ward II, Minglanilla 6046, Cebu");
        page.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 260, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("(032) 326 3677 / (032) 497 0767");
        page.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("www.stcecilia.edu.ph");
        page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 260, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("sccreq@gmail.com");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("_____________________________________________________________________");
        page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 485, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" STUDENTS    CASH    ASSISTANCE    SYSTEM");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 485, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Applicant Name:");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Program Name:");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cash Release:");
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("CASH ASSISTANCE RESULT");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 20));

        progname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        progname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(progname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, 20));

        appname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(appname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, 20));

        cash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 240, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/st-cecilia-carlo-dolci-modified.png"))); // NOI18N
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, 100));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scc (1).png"))); // NOI18N
        page.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 100));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 620, 290));

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 110, 40));

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dbConnector db = new dbConnector();
    JPanel myPanel = new JPanel();
    Session sess = Session.getInstance();
    db.logActivity(sess.getUid(), "Printed Cash Assistance Result Program Name: "+progname.getText());
    PanelPrinter pPrint = new PanelPrinter(page);
    pPrint.printPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    cashReleasing cr = new cashReleasing();
    cr.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printAssistanceResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printAssistanceResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printAssistanceResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printAssistanceResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create over5y the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printAssistanceResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel appname;
    public javax.swing.JLabel cash;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel page;
    public javax.swing.JLabel progname;
    // End of variables declaration//GEN-END:variables
}
